# Generated by Django 2.0.5 on 2018-06-08 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Reddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_reddits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
