# Generated by Django 2.0.5 on 2018-06-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_clone', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sub_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comment', to='reddit_clone.Comment'),
        ),
    ]
